NeshatSazan/Areas/administration/Controllers/PodcastController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.PublicClass;
using ServiceLayer.ViewModels.Admin.PodcastViewModels;

namespace NeshatSazan.Areas.administration.Controllers
{
    [Area(nameof(administration))]
	[PermissionChecker(7)]
	public class PodcastController : Controller
    {
        private readonly IPodcast _Podcast;

        public PodcastController(IPodcast podcast)
        {
            _Podcast = podcast;
        }

        [HttpGet]
		[PermissionChecker(7)]
		public IActionResult Index(int pageId = 1, string search = "")
        {
            var project = _Podcast.GetAllAdmin(pageId, search);
            return View(project);
        }

        [HttpGet]
		[PermissionChecker(63)]
		public IActionResult Recovery(int pageId = 1, string search = "")
        {
            var project = _Podcast.GetDeleteAdmin(pageId, search);
            return View(project);
        }

        [HttpGet]
		[PermissionChecker(59)]
		public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
		[PermissionChecker(59)]
		public IActionResult Create(CreatePodcastViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _Podcast.Create(model);
                if (result.IsSuccedded == false)
                {
                    TempData["error"] = result.Message;
                }
                else
                {
                    TempData["success"] = result.Message;
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["warning"] = "لطفا فیلد های اجباری را پر کنید";
            return View(model);
        }

        [HttpGet]
		[PermissionChecker(60)]
		public IActionResult Delete(long id)
        {
            var result = _Podcast.Delete(id);
            if (result.IsSuccedded == false)
            {
                TempData["error"] = result.Message;
            }
            else
            {
                TempData["success"] = result.Message;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
		[PermissionChecker(62)]
		public IActionResult GetRecovery(long id)
        {
            var result = _Podcast.Recovery(id);
            if (result.IsSuccedded == false)
            {
                TempData["error"] = result.Message;
            }
            else
            {
                TempData["success"] = result.Message;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
		[PermissionChecker(60)]
		public IActionResult Edit(long id)
        {
            var model = _Podcast.GetDetails(id);
            return View(model);
        }

        [HttpPost]
		[PermissionChecker(60)]
		public IActionResult Edit(EditPodcastViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _Podcast.Edit(model);
                if (result.IsSuccedded == false)
                {
                    TempData["error"] = result.Message;
                }
                else
                {
                    TempData["success"] = result.Message;
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["warning"] = "لطفا فیلد های اجباری را پر کنید";
            return View(model);
        }

    }
}

NeshatSazan/Areas/administration/Views/Podcast/Create.cshtml
@model ServiceLayer.ViewModels.Admin.PodcastViewModels.CreatePodcastViewModel

@{
    Layout = "~/areas/administration/views/shared/_AdminLayout.cshtml";
    ViewData["Title"] = "ایجاد کلیپ یا پادکست جدید";
}
<div class="card">
    <div class="modal-header">
        <h4 class="modal-title">@ViewData["Title"]</h4>
    </div>

    <form asp-action="Create" asp-controller="Podcast"
          method="post"
          data-action="Refresh"
          enctype="multipart/form-data">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Language" class="form-label">انمتخاب زبان</label>
                        <select type="text" class="form-select" asp-for="Language">
                            <option value="0">فارسی</option>
                            <option value="1">انگلیسی</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Title" class="form-label"></label>
                        <input type="text" class="form-control" id="Name1" asp-for="Title" onchange="makeSlug('Name1', 'Slug')">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Slug" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="Slug">
                        <span asp-validation-for="Slug" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Picture" class="form-label"></label>
                        <input type="file" class="form-control" asp-for="Picture" accept="Image/*">
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Video" class="form-label"></label>
                        <input type="file" class="form-control" asp-for="Video" accept="video/*">
                        <span asp-validation-for="Video" class="text-danger"></span>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureAlt" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureTitle" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="text-danger"></span>
                    </div>
                </div>
            </div>


        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
        </div>
    </form>
</div>

NeshatSazan/Areas/administration/Views/Podcast/Edit.cshtml
@model ServiceLayer.ViewModels.Admin.PodcastViewModels.EditPodcastViewModel

@{
    Layout = "~/Areas/administration/Views/Shared/_Layout_Null.cshtml";
}
<div class="card">
    <div class="modal-header">
        <h4 class="modal-title">ویرایش : @Model.Title</h4>
    </div>

    <form asp-action="Edit" asp-controller="Podcast"
          method="post"
          data-action="Refresh"
          enctype="multipart/form-data">
        <div class="modal-body">
            <input hidden asp-for="Id" />
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Language" class="form-label">انمتخاب زبان</label>
                        <select type="text" class="form-select" asp-for="Language">
                            <option value="0">فارسی</option>
                            <option value="1">انگلیسی</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Title" class="form-label"></label>
                        <input type="text" class="form-control" id="Name1" asp-for="Title" onchange="makeSlug('Name1', 'Slug')">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Slug" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="Slug">
                        <span asp-validation-for="Slug" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Picture" class="form-label"></label>
                        <input type="file" class="form-control" asp-for="Picture" accept="Image/*">
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <img controls width="245" height="230" src="~/ViewPicture/@Model.pictureStr" />
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Video" class="form-label"></label>
                        <input type="file" class="form-control" asp-for="Video" accept="video/*">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <video controls width="245" height="230">
                            <source src="~/ViewPicture/@Model.videoStr">
                        </video>
                        @*<video src="~/Viewvideo/@Model.videoStr" width="150" height="150" />*@
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureAlt" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureTitle" class="form-label"></label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="text-danger"></span>
                    </div>
                </div>
            </div>



        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
        </div>
    </form>
</div>

NeshatSazan/Areas/administration/Views/Podcast/Index.cshtml
@using ServiceLayer.ViewModels.Admin.PodcastViewModels
@using ServiceLayer.ViewModels
@model BaseFilterViewModel<ListPodcastViewModel>
@{
    ViewData["Title"] = "لیست کلیپ ها و پادکست ها";
    Layout = "~/Areas/administration/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="pe-3"><h4 class="page-title">@ViewData["title"]</h4></div>

    <div class="ms-auto">
        <a class="btn btn-success btn-lg" href="/Administration/Podcast/create">ایجاد</a>
    </div>
</div>
<hr />

<div class="card">
    <div class="card-header">
        <form method="get" asp-action="Index" id="formFilter">
            <input hidden value="@Model.PageIndex" id="pageId" name="pageId" />
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="pe-3"><h4 class="page-title"> <input type="search" name="search" class="form-control form-control-sm" placeholder="جستجو"></h4></div>

                <div class="ms-auto">
                    <button class="btn btn-info " type="submit">جستجو</button>
                    <a class="btn btn-info " href="/Administration/Podcast">نمایش همه</a>
                    <a class="btn btn-danger " href="/Administration/Podcast/Recovery">نمایش حذف شده ها</a>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">زبان</th>
                    <th scope="col">عنوان</th>
                    <th scope="col">تاریخ ثبت</th>
                    <th scope="col">حذف شده</th>
                    <th scope="col">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }

                @foreach (var item in Model.Entities)
                {
                    <tr>
                        <th scope="row">@counter</th>
                        <td>
                            @if (item.Language == "0")
                            {
                                <p>فارسی</p>
                            }
                            @if (item.Language == "1")
                            {
                                <p>انگلیسی</p>
                            }
                        </td>
                        <td>@item.Title</td>
                        <td>@item.CreationDate</td>
                        <td>

                            @if (!item.IsRemoved)
                            {
                                <p class="text-success">موجود</p>
                            }
                            @if (item.IsRemoved)
                            {
                                <p class="text-danger">حذف شده</p>
                            }
                        </td>
                        <td>
                            <a href="/Administration/Podcast/Edit/@item.Id" class="btn btn-warning">
                                ویرایش
                            </a>
                            <a asp-action="Delete" asp-controller="Podcast" asp-route-id="@item.Id" class="btn btn-danger">
                                حذف
                            </a>

                        </td>
                    </tr>
                    counter++;
                }

            </tbody>
        </table>
    </div>

    <div class="card-footer">
        @if (Model.PageCount > 1)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.PageIndex > Model.StartPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Previous">
                                <span aria-hidden="true">«</span>
                            </a>
                        </li>
                    }
                    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                    {
                        <li class="page-item">
                            <a class="page-link paginations @(Model.PageIndex == i ? "active" : "")" href="javascript:;">@i</a>
                        </li>
                    }

                    @if (Model.PageIndex < Model.EndPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Next">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                    }

                </ul>
            </nav>
        }

    </div>
</div>
  




@section Scripts{
   
    <script>
        $(document).ready(function () {
            $(".paginations").click(function () {
                $("#pageId").val($(this).text());
                $("#formFilter").submit();
            })
        }
        )
    </script>
                }

NeshatSazan/Areas/administration/Views/Podcast/Recovery.cshtml
@using ServiceLayer.ViewModels.Admin.PodcastViewModels
@using ServiceLayer.ViewModels
@model BaseFilterViewModel<ListPodcastViewModel>
@{
    ViewData["Title"] = " لیست کلیپ ها و پادکست ها حذف شده";
    Layout = "~/Areas/administration/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="pe-3"><h4 class="page-title">@ViewData["title"]</h4></div>

</div>
<hr />

<div class="card">
    <div class="card-header">
        <form method="get" asp-action="Recovery" id="formFilter">
            <input hidden value="@Model.PageIndex" id="pageId" name="pageId" />
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="pe-3"><h4 class="page-title"> <input type="search" name="search" class="form-control form-control-sm" placeholder="جستجو"></h4></div>

                <div class="ms-auto">
                    <button class="btn btn-info " type="submit">جستجو</button>
                    <a class="btn btn-info " href="/Administration/Podcast">نمایش همه</a>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">زبان</th>
                    <th scope="col">عنوان</th>
                    <th scope="col">تاریخ ثبت</th>
                    <th scope="col">حذف شده</th>
                    <th scope="col">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }

                @foreach (var item in Model.Entities)
                {
                    <tr>
                        <th scope="row">@counter</th>
                        <td>
                            @if (item.Language == "0")
                            {
                                <p>فارسی</p>
                            }
                            @if (item.Language == "1")
                            {
                                <p>انگلیسی</p>
                            }
                        </td>
                        <td>@item.Title</td>
                        <td>@item.CreationDate</td>
                        <td>

                            @if (!item.IsRemoved)
                            {
                                <p class="text-success">موجود</p>
                            }
                            @if (item.IsRemoved)
                            {
                                <p class="text-danger">حذف شده</p>
                            }
                        </td>
                        <td>

                            <a asp-action="GetRecovery" asp-controller="Podcast" asp-route-id="@item.Id" class="btn btn-info">
                                بازگردانی
                            </a>



                        </td>
                    </tr>
                    counter++;
                }

            </tbody>
        </table>
    </div>

    <div class="card-footer">
        @if (Model.PageCount > 1)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.PageIndex > Model.StartPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Previous">
                                <span aria-hidden="true">«</span>
                            </a>
                        </li>
                    }
                    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                    {
                        <li class="page-item">
                            <a class="page-link paginations @(Model.PageIndex == i ? "active" : "")" href="javascript:;">@i</a>
                        </li>
                    }

                    @if (Model.PageIndex < Model.EndPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Next">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                    }

                </ul>
            </nav>
        }

    </div>
</div>
         

<div class="modal" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">

        <div id="bodyModal" class="modal-content">
        </div>


    </div>
</div>





@section Scripts{

    <script>
        $(document).ready(function () {
            $(".paginations").click(function () {
                $("#pageId").val($(this).text());
                $("#formFilter").submit();
            })
        }
        )
    </script>
                }