NeshatSazan/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.ViewModels.Client.Farsi.Footer;

namespace NeshatSazan.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly IQueryClients _Iquery;
		public FooterViewComponent(IQueryClients iquery)
        {
           _Iquery = iquery;
        }

        public IViewComponentResult Invoke()
        {
            var result = new FooterViewModel
            {
                siteInfoFooter = _Iquery.GetSiteInfoFarsiFooter(),
                SettingMenu = _Iquery.GetSettingsFarsiMenus(),
            };

            return View(result);
        }
    }
}

NeshatSazan/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;
using ServiceLayer.ViewModels.Client.Farsi.Menu;

namespace NeshatSazan.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IQueryClients _Iquery;
        public MenuViewComponent(IQueryClients iquery)
        {
           _Iquery = iquery;
        }

        public IViewComponentResult Invoke()
        {
            var result = new MenuViewModel
            {
                siteInfoMenu = _Iquery.GetSiteInfoFarsiMenus(),
                SettingMenu = _Iquery.GetSettingsFarsiMenus(),
                ArticleCategory = _Iquery.GetArticleCategoryFarsi(),
            };

            return View(result);
        }
    }
}

NeshatSazan/Views/Shared/Components/_Layout11.cshtml
<!DOCTYPE html>
<html lang="rtl">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    @if (ViewData["Title"] != null)
    {
        <title>@ViewData["Title"] - نشاط سازان</title>
    }
    else
    {
        <title>نشاط سازان</title>
    }
    <meta name="keywords" content="@ViewData["keywords"]" />
    <meta name="description" content="@ViewData["metaDescription"]" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/ViewPicture/Icon/IconSite.ico" type="image/x-icon">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Porto/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/animate/animate.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Porto/vendor/magnific-popup/magnific-popup.min.css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Porto/css/theme.css">
    <link rel="stylesheet" href="~/Porto/css/theme-elements.css">
    <link rel="stylesheet" href="~/Porto/css/theme-blog.css">
    <link rel="stylesheet" href="~/Porto/css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet" href="~/Porto/vendor/rs-plugin/css/settings.css">
    <link rel="stylesheet" href="~/Porto/vendor/rs-plugin/css/layers.css">
	<link rel="stylesheet" href="~/Porto/vendor/rs-plugin/css/navigation.css">
    <link rel="stylesheet" href="~/portoEn/vendor/nivo-slider/nivo-slider.css">
    <link rel="stylesheet" href="~/portoEn/vendor/nivo-slider/themes/default/default.css">
	<link rel="stylesheet" href="~/Porto/vendor/circle-flip-slideshow/css/component.css">
	<!-- Demo CSS -->
	<link rel="stylesheet" href="~/Porto/css/demos/demo-construction.css">
	<!-- Skin CSS -->
	<link rel="stylesheet" href="~/Porto/css/skins/skin-construction.css">

	

	<!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Porto/css/custom.css">

    <!-- Head Libs -->
    <script src="~/Porto/vendor/modernizr/modernizr.min.js"></script>

</head>
<body class="loading-overlay-showing" data-target="#sidebar" data-plugin-page-transition data-loading-overlay data-plugin-options="{'hideDelay': 500}">
	<div class="loading-overlay">
		<div class="bounce-loader">
			<div class="bounce1"></div>
			<div class="bounce2"></div>
			<div class="bounce3"></div>
		</div>
	</div>

	<div class="body">
		@await Component.InvokeAsync("Menu")
		<div role="main" class="main">			
			
					@RenderBody()	

			
		</div>

		@await Component.InvokeAsync("Footer")
	
		
	</div>

 

    

    <!-- Vendor -->
    <script src="~/Porto/vendor/jquery/jquery.min.js"></script>
    <script src="~/Porto/vendor/jquery.appear/jquery.appear.min.js"></script>
    <script src="~/Porto/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/Porto/vendor/jquery.cookie/jquery.cookie.min.js"></script>
    <script src="~/Porto/vendor/popper/umd/popper.min.js"></script>
    <script src="~/Porto/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Porto/vendor/common/common.min.js"></script>
    <script src="~/Porto/vendor/jquery.validation/jquery.validate.min.js"></script>
    <script src="~/Porto/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/Porto/vendor/jquery.gmap/jquery.gmap.min.js"></script>
    <script src="~/Porto/vendor/jquery.lazyload/jquery.lazyload.min.js"></script>
    <script src="~/Porto/vendor/isotope/jquery.isotope.min.js"></script>
    <script src="~/Porto/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/Porto/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="~/Porto/vendor/vide/jquery.vide.min.js"></script>
    <script src="~/Porto/vendor/vivus/vivus.min.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Porto/js/theme.js"></script>

    <!-- Current Page Vendor and Views -->
	<script src="~/Porto/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
	<script src="~/Porto/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
	<script src="~/Porto/vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
	<script src="~/Porto/js/views/view.home.js"></script>
    <script src="~/Porto/vendor/nivo-slider/jquery.nivo.slider.min.js"></script>
    <script src="~/Porto/js/views/view.contact.js"></script>

    <!-- Current Page Vendor and Views -->
    <script src="~/Porto/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Porto/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

    <!-- Demo -->
    <script src="~/portoEn/js/demos/demo-construction.js"></script>

	<!-- Theme Custom -->
    <script src="~/Porto/js/custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Porto/js/theme.init.js"></script>

	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>




    <!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-12345678-1', 'auto');
        ga('send', 'pageview');
    </script>
     -->
	<script src="~/js/signalr.js"></script>
	<script src="~/js/signalRView.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>