NeshatSazan/Areas/administration/Controllers/SlideHeaderController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.PublicClass;
using ServiceLayer.Services.Interfaces;
using ServiceLayer.ViewModels.Admin.SlideViewModels;

namespace NeshatSazan.Areas.Administration.Controllers
{
    [Area(nameof(administration))]
	[PermissionChecker(2)]
	public class SlideHeaderController : Controller
    {
        private readonly ISlide _Slides;

        public SlideHeaderController(ISlide slides)
        {
            _Slides = slides;
        }

        [HttpGet]
		[PermissionChecker(2)]
		public IActionResult Index(int pageId = 1, string search = "")
        {
            var slide = _Slides.GetAllAdmin(pageId, search);
            return View(slide);
        }

        [HttpGet]
		[PermissionChecker(20)]
		public IActionResult Recovery(int pageId = 1, string search = "")
        {
            var slide = _Slides.GetDeleteAdmin(pageId, search);
            return View(slide);
        }

		[PermissionChecker(18)]
		public IActionResult Remove(long id)
        {
            _Slides.Remove(id);
            return RedirectToAction(nameof(Index));
        }

		[PermissionChecker(19)]
		public IActionResult Restore(long id)
        {
            _Slides.Restore(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
		[PermissionChecker(16)]
		public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
		[PermissionChecker(16)]
		public IActionResult Create(CreateSlideViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _Slides.Create(viewModel);
                if (result.IsSuccedded == false)
                {
                    TempData["error"] = result.Message;
                }
                else
                {
                    TempData["success"] = result.Message;
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["warning"] = "لطفا فیلد های اجباری را پر کنید";
            return View(viewModel);
        }

        [HttpGet]
		[PermissionChecker(17)]
		public IActionResult Edit(long id)
        {
            var slide = _Slides.GetDetails(id);
            return View(slide);
        }

        [HttpPost]
		[PermissionChecker(17)]
		public IActionResult Edit(EditSlideViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = _Slides.Edit(viewModel);
                if (result.IsSuccedded == false)
                {
                    TempData["error"] = result.Message;
                }
                else
                {
                    TempData["success"] = result.Message;
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["warning"] = "لطفا فیلد های اجباری را پر کنید";
            return View(viewModel);
        }
    }
}

NeshatSazan/Areas/administration/Views/SlideHeader/Create.cshtml
@model ServiceLayer.ViewModels.Admin.SlideViewModels.CreateSlideViewModel
@{
    Layout = "~/areas/administration/views/shared/_AdminLayout.cshtml";
    ViewData["Title"] = "ایجاد اسلاید جدید";
}

<div class="card">
    <div class="modal-header">
        <h4 class="modal-title">@ViewData["Title"]</h4>
    </div>

    <form asp-controller="SlideHeader" asp-action="Create"
          method="post"
          data-action="Refresh"
          enctype="multipart/form-data">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Language" class="form-label">انمتخاب زبان</label>
                        <select type="text" class="form-select" asp-for="Language">
                            <option value="0">فارسی</option>
                            <option value="1">انگلیسی</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Picture" class="form-label">عکس</label>
                        <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureAlt" class="form-label">Alt</label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureTitle" class="form-label">عنوان عکس</label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Heading" class="form-label">سرتیتر</label>
                        <input type="text" class="form-control" asp-for="Heading">
                        <span asp-validation-for="Heading" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Title" class="form-label">عنوان</label>
                        <input type="text" class="form-control" asp-for="Title">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Text" class="form-label">متن</label>
                        <input type="text" class="form-control" asp-for="Text">
                        <span asp-validation-for="Text" class="text-danger"></span>
                    </div>
                </div>
                
            </div>
          
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
        </div>
    </form>
</div>

NeshatSazan/Areas/administration/Views/SlideHeader/Edit.cshtml
@model ServiceLayer.ViewModels.Admin.SlideViewModels.EditSlideViewModel
@{
    Layout = "~/areas/administration/views/shared/_AdminLayout.cshtml";
    ViewData["Title"] = "ویرایش اسلاید ";
}

<div class="card">
    <div class="modal-header">
        <h4 class="modal-title">ویرایش اسلاید: @Model.Heading</h4>
    </div>

    <form asp-controller="SlideHeader" asp-action="Edit"
          method="post"
          data-action="Refresh"
          enctype="multipart/form-data">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Language" class="form-label">انمتخاب زبان</label>
                        <select type="text" class="form-select" asp-for="Language">
                            <option value="0">فارسی</option>
                            <option value="1">انگلیسی</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Picture" class="form-label">عکس</label>
                        <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureAlt" class="form-label">Alt</label>
                        <input type="text" class="form-control" asp-for="PictureAlt">
                        <span asp-validation-for="PictureAlt" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="PictureTitle" class="form-label">عنوان عکس</label>
                        <input type="text" class="form-control" asp-for="PictureTitle">
                        <span asp-validation-for="PictureTitle" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Heading" class="form-label">سرتیتر</label>
                        <input type="text" class="form-control" asp-for="Heading">
                        <span asp-validation-for="Heading" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        <label asp-for="Title" class="form-label">عنوان</label>
                        <input type="text" class="form-control" asp-for="Title">
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Text" class="form-label">متن</label>
                        <input type="text" class="form-control" asp-for="Text">
                        <span asp-validation-for="Text" class="text-danger"></span>
                    </div>
                </div>
                
            </div>
            
            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
        </div>
    </form>
</div>

NeshatSazan/Areas/administration/Views/SlideHeader/Index.cshtml
@using ServiceLayer.ViewModels.Admin.SlideViewModels
@using ServiceLayer.ViewModels
@model BaseFilterViewModel<SlideViewModel>

@{
    Layout = "~/areas/administration/views/shared/_AdminLayout.cshtml";
    ViewData["Title"] = "مدیریت عکس اسلایدر";

}

<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="pe-3"><h4 class="page-title">@ViewData["title"]</h4></div>

    <div class="ms-auto">
        <a class="btn btn-success btn-lg" href="/administration/SlideHeader/Create">ایجاد</a>
    </div>
</div>
<hr />

<div class="card">
    <div class="card-header">
        <form method="get" asp-action="Index" id="formFilter">
            <input hidden value="@Model.PageIndex" id="pageId" name="pageId" />
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="pe-3"><h4 class="page-title"> <input type="search" name="search" class="form-control form-control-sm" placeholder="جستجو"></h4></div>

                <div class="ms-auto">
                    <button class="btn btn-info " type="submit">جستجو</button>
                    <a class="btn btn-info " href="/Administration/SlideHeader">نمایش همه</a>
                    <a class="btn btn-danger " href="/Administration/SlideHeader/Recovery">نمایش حذف شده ها</a>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>زبان</th>
                    <th>عکس</th>
                    <th>سرتیتر</th>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th>تاریخ تولید</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }
                @foreach (var item in Model.Entities)
                {
                    <tr>
                        <td>@counter</td>
                        <td>
                            @if (item.Language == "0")
                            {
                                <p>فارسی</p>
                            }
                            @if (item.Language == "1")
                            {
                                <p>انگلیسی</p>
                            }
                        </td>
                        <td>
                            <img src="~/ViewPicture/@item.Picture" style="width: 40px; height: 40px" />
                        </td>
                        <td>@item.Heading</td>
                        <td>@item.Title</td>
                        <td>
                            @if (!item.IsRemoved)
                            {
                                <i class="text-success"> موجود</i>
                            }
                            else
                            {
                                <i class="text-danger"> حذف</i>
                            }
                        </td>
                        <td>@item.CreationDate</td>
                        <td>
                            <a class="btn btn-warning" href="/administration/SlideHeader/edit/@item.Id">
                                ویرایش
                            </a>
                            @if (!item.IsRemoved)
                            {
                                <a class="btn btn-danger"
                                   asp-controller="SlideHeader" asp-action="Remove" asp-route-id="@item.Id">
                                    حذف عکس
                                </a>

                            }
                            else
                            {
                                <a class="btn btn-success"
                                   href="/administration/SlideHeader/Restore/@item.Id">
                                    بازگردانی عکس
                                </a>
                            }

                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        @if (Model.PageCount > 1)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.PageIndex > Model.StartPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Previous">
                                <span aria-hidden="true">«</span>
                            </a>
                        </li>
                    }
                    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                    {
                        <li class="page-item">
                            <a class="page-link paginations @(Model.PageIndex == i ? "active" : "")" href="javascript:;">@i</a>
                        </li>
                    }

                    @if (Model.PageIndex < Model.EndPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Next">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                    }

                </ul>
            </nav>
        }

    </div>
</div>

<div class="modal" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">

        <div id="bodyModal" class="modal-content">
        </div>


    </div>
</div>


@section Scripts {
   
    <script>
        $(document).ready(function () {
            $(".paginations").click(function () {
                $("#pageId").val($(this).text());
                $("#formFilter").submit();
            })
        }
        )
    </script>
    }

NeshatSazan/Areas/administration/Views/SlideHeader/Recovery.cshtml
@using ServiceLayer.ViewModels.Admin.SlideViewModels
@using ServiceLayer.ViewModels
@model BaseFilterViewModel<SlideViewModel>

@{
    Layout = "~/areas/administration/views/shared/_AdminLayout.cshtml";
    ViewData["Title"] = "مدیریت عکس اسلایدر";

}

<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="pe-3"><h4 class="page-title">@ViewData["title"]</h4></div>

   
</div>
<hr />

<div class="card">
    <div class="card-header">
        <form method="get" asp-action="Index" id="formFilter">
            <input hidden value="@Model.PageIndex" id="pageId" name="pageId" />
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="pe-3"><h4 class="page-title"> <input type="search" name="search" class="form-control form-control-sm" placeholder="جستجو"></h4></div>

                <div class="ms-auto">
                    <button class="btn btn-info " type="submit">جستجو</button>
                    <a class="btn btn-info " href="/Administration/SlideHeader">نمایش همه</a>
                </div>
            </div>
        </form>
    </div>
    <div class="card-body">
        <table class="table mb-0 table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>زبان</th>
                    <th>عکس</th>
                    <th>سرتیتر</th>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th>تاریخ تولید</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                }
                @foreach (var item in Model.Entities)
                {
                    <tr>
                        <td>@counter</td>
                        <td>
                            @if (item.Language == "0")
                            {
                                <p>فارسی</p>
                            }
                            @if (item.Language == "1")
                            {
                                <p>انگلیسی</p>
                            }
                        </td>
                        <td>
                            <img src="~/ViewPicture/@item.Picture" style="width: 40px; height: 40px" />
                        </td>
                        <td>@item.Heading</td>
                        <td>@item.Title</td>
                        <td >
                            @if (!item.IsRemoved)
                            {
                                <p class="text-success">موجود</p>
                            }
                            else
                            {
                                <p class="text-danger">حذف</p>
                            }
                        </td>
                        <td>@item.CreationDate</td>
                        <td>
                            @if (!item.IsRemoved)
                            {
                                <a class="btn btn-danger"
                                   asp-controller="SlideHeader" asp-action="Remove" asp-route-id="@item.Id">
                                    حذف
                                </a>

                            }
                            else
                            {
                                <a class="btn btn-success"
                                   href="/administration/SlideHeader/Restore/@item.Id">
                                    بازگردانی عکس
                                </a>
                            }

                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        @if (Model.PageCount > 1)
        {
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    @if (Model.PageIndex > Model.StartPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Previous">
                                <span aria-hidden="true">«</span>
                            </a>
                        </li>
                    }
                    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                    {
                        <li class="page-item">
                            <a class="page-link paginations @(Model.PageIndex == i ? "active" : "")" href="javascript:;">@i</a>
                        </li>
                    }

                    @if (Model.PageIndex < Model.EndPage)
                    {
                        <li class="page-item">
                            <a class="page-link" href="javascript:;" aria-label="Next">
                                <span aria-hidden="true">»</span>
                            </a>
                        </li>
                    }

                </ul>
            </nav>
        }

    </div>
</div>


@section Scripts {
   
    <script>
        $(document).ready(function () {
            $(".paginations").click(function () {
                $("#pageId").val($(this).text());
                $("#formFilter").submit();
            })
        }
        )
    </script>
    }